<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cayla Salsa Azhar">
<meta name="dcterms.date" content="2025-01-03">

<title>Analisis Pengaruh Ekspor dan Impor terhadap Pertumbuhan Ekonomi di Indonesia (2013 - 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Ekspor dan Impor terhadap Pertumbuhan Ekonomi di Indonesia (2013 - 2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cayla Salsa Azhar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi merupakan salah satu indikator utama untuk menilai keberhasilan pembangunan suatu negara. Di Indonesia, pertumbuhan ekonomi mempunyai peranan strategis dalam meningkatkan kesejahteraan masyarakat, mengurangi kemiskinan dan menciptakan lapangan kerja. Salah satu penyumbang terbesar pertumbuhan ekonomi adalah sektor perdagangan internasional, khususnya impor dan ekspor.</p>
<p>Ekspor merupakan mesin utama perekonomian, meningkatkan penerimaan devisa, mendorong pertumbuhan industri dalam negeri, dan meningkatkan pangsa pasar global. Di sisi lain, impor berperan penting dalam memenuhi kebutuhan bahan baku, teknologi, dan barang modal, terutama yang tidak tersedia di dalam negeri, dan pada akhirnya menunjang aktivitas manufaktur negara.</p>
<p>Namun hubungan antara ekspor dan impor dengan pertumbuhan ekonomi seringkali dipengaruhi oleh berbagai faktor, antara lain kebijakan perdagangan, fluktuasi nilai tukar, harga komoditas global, dan kondisi pasar internasional. Ketergantungan Indonesia pada ekspor bahan mentah seperti kelapa sawit, batu bara, dan karet membuat perekonomian dalam negeri rentan terhadap fluktuasi harga di pasar dunia. Selain itu, peningkatan impor barang konsumsi dapat menyebabkan defisit perdagangan yang pada akhirnya mempengaruhi stabilitas perekonomian.</p>
<p>Dalam konteks ini, penting untuk menganalisis dampak impor dan ekspor terhadap pertumbuhan ekonomi Indonesia. Pemahaman pola dan dampak memungkinkan pemerintah mengembangkan kebijakan yang tepat untuk mengoptimalkan peran perdagangan internasional dalam mendorong pembangunan ekonomi berkelanjutan.</p>
<p>Tujuan penelitian ini adalah untuk mengetahui sejauh mana kontribusi impor dan ekspor terhadap pertumbuhan ekonomi Indonesia dan mengidentifikasi faktor-faktor yang mempengaruhi hubungan tersebut. Oleh karena itu, hasil analisis ini diharapkan dapat memberikan rekomendasi yang bermanfaat bagi pengambilan kebijakan di bidang perdagangan dan perekonomian.</p>
<hr>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini mencakup analisis kuantitatif mengenai pengaruh ekspor dan impor terhadap pertumbuhan ekonomi Indonesia. Fokus utama memahami hubungan kausalitas, kontribusi relatif, serta dampak fluktuasi ekspor dan impor terhadap produk domestik bruto (PDB). Periode penelitian mencakup data historis selama 10 tahun terakhir, seperti tahun 2013–2023, untuk mengamati tren dan perubahan struktural dalam perdagangan internasional serta dampaknya terhadap perekonomian nasional. Penelitian ini berfokus pada ekonomi Indonesia secara agregat, dengan pembahasan tambahan terkait sektor-sektor utama dalam ekspor, seperti agribisnis, pertambangan, dan manufaktur, serta sektor impor, terutama bahan baku, barang modal, dan barang konsumsi.</p>
<p>Variabel yang dianalisis meliputi nilai ekspor, nilai impor, dan neraca perdagangan sebagai variabel independen, sedangkan tingkat pertumbuhan ekonomi (PDB) sebagai variabel dependen. Faktor-faktor lain seperti nilai tukar rupiah, tingkat inflasi, harga komoditas internasional, dan kebijakan perdagangan dimasukkan sebagai variabel kontrol. Penelitian ini menggunakan pendekatan ekonometrik, seperti analisis regresi linier berganda atau model Vector Autoregression (VAR), untuk mengevaluasi hubungan antara variabel-variabel tersebut. World Bank digunakan sebagai sumber utama data.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Bagaimana pengaruh ekspor terhadap pertumbuhan ekonomi Indonesia</li>
<li>Bagaimana pengaruh impor terhadap pertumbuhan ekonomi Indonesia?</li>
<li>Sejauh mana hubungan antara ekspor dan impor dengan pertumbuhan ekonomi nasional?</li>
<li>Faktor-faktor apa saja yang memengaruhi hubungan antara ekspor, impor, dan pertumbuhan ekonomi di Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini adalah menganalisis dampak impor dan ekspor terhadap pertumbuhan ekonomi di Indonesia. penelitian ini juga bertujuan untuk mengetahui hubungan ekspor, impor dengan pertumbuhan ekonomi nasional serta menjelaskan faktor-faktor yang mempengaruhi hubungan tersebut. sedangkan memiliki manfaat Secara akademis, penelitian ini dapat memperkaya literatur ekonomi, khususnya mengenai pertumbuhan ekonomi dan perdagangan internasional. Ini juga dapat berfungsi sebagai referensi untuk penelitian yang akan datang. Penelitian ini dapat membantu para pembuat kebijakan membuat strategi perdagangan yang mendukung pertumbuhan ekonomi yang berkelanjutan. Studi ini juga akan membantu para pelaku ekonomi memahami dampak perdagangan internasional terhadap perekonomian negara dan bagaimana memaksimalkan peluang ekspor dan impor. Secara lebih luas, tujuan dari penelitian ini adalah untuk meningkatkan pemahaman masyarakat tentang seberapa penting perdagangan internasional bagi kesejahteraan perekonomian nasional.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#/warning: false</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#/echo: true</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.4.2</code></pre>
</div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li>Ekspor</li>
</ol>
<p>Ekspor adalah kegiatan mengeluarkan barang dari daerah pabean. Menurut Lipsey (1995), ekspor dapat diartikan sebagai total penjualan barang yang dapat dihasilkan oleh suatu negara, kemudian diperdagangkan kepada negara lain dengan tujuan mendapatkan devisa. Suatu negara dapat mengekspor barang-barang yang dihasilkannya ke negara lain yang tidak dapat menghasilkan barang-barang yang dihasilkan negara pengekspor. Menurut Salvatore (1997), terdapat beberapa alasan sehingga dilakukannya ekspor oleh suatu negara, antara lain:</p>
<p>a. Keinginan untuk memenuhi berbagai kebutuhan yang tidak dapat dipenuhi dari produksi atau hasil dalam negeri, termasuk kebutuhan yang dapat diproduksi namun diperlukan biaya yang lebih tinggi dibandingkan jika diproduksi di luar negeri.</p>
<p>b. Keinginan suatu negara untuk memperluas pemasaran komoditas domestik untuk meningkatkan sumber devisa bagi kegiatan pembangunan.</p>
<ol start="2" type="1">
<li>Impor</li>
</ol>
<p>Impor adalah kegiatan ekonomi pembelian barang dan jasa dari luar negeri untuk memenuhi kebutuhan dalam negeri. Dalam perdagangan internasional, impor terjadi ketika suatu negara tidak dapat memproduksi barang atau jasa tertentu secara efisien, atau ketika barang yang diproduksi di negara lain memiliki kualitas yang lebih baik atau harga yang lebih kompetitif. Impor mempunyai peranan penting dalam menunjang kegiatan perekonomian masyarakat. Misalnya, bahan baku dan barang modal impor yang sering digunakan dalam proses produksi dalam negeri dan mendukung pertumbuhan sektor industri. Pemerintah biasanya mengatur aktivitas impor melalui kebijakan tarif, kuota, atau peraturan lainnya untuk melindungi industri dalam negeri dan menjaga keseimbangan ekonomi.</p>
<ol start="3" type="1">
<li>Pertumbuhan Ekonomi</li>
</ol>
<p>Pertumbuhan ekonomi Indonesia yang dipengaruhi oleh ekspor dan impor menunjukkan dinamika yang kompleks. Ekspor berkontribusi secara signifikan terhadap peningkatan pendapatan negara, terutama dari sektor komoditas utama seperti batu bara, minyak kelapa sawit, dan karet. Namun, ketergantungan pada komoditas mentah membuat ekonomi Indonesia rentan terhadap fluktuasi harga global. Di sisi lain, impor memainkan peran penting dalam memenuhi kebutuhan bahan baku dan barang modal untuk mendukung aktivitas produksi domestik. Ketidakseimbangan antara ekspor dan impor, seperti tingginya impor barang konsumsi dibandingkan nilai ekspor, dapat menyebabkan defisit neraca perdagangan yang berpengaruh pada stabilitas ekonomi. Oleh karena itu, optimalisasi ekspor barang bernilai tambah serta pengelolaan impor yang efektif diperlukan untuk mendorong pertumbuhan ekonomi yang berkelanjutan.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai ekspor, impor, dan pertumbuhan Ekonomi di indonesia dengan satuan USD.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Tahun</th>
<th>X (Ekspor)</th>
<th>Y (impor)</th>
<th>U (pertumbuhan ekonomi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>23,9235763793605</td>
<td>24,7137962959288</td>
<td>5,5572636889101</td>
</tr>
<tr class="even">
<td>2014</td>
<td>23,6659845969367</td>
<td>24,414190988586</td>
<td>5,006668425755</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>21,1601792598059</td>
<td>20,7774609817235</td>
<td>4,87632230022123</td>
</tr>
<tr class="even">
<td>2016</td>
<td>19,0889938536664</td>
<td>18,3323479486654</td>
<td>5,03306918280177</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>20,1773044351106</td>
<td>19,17819263535</td>
<td>5,06978590134916</td>
</tr>
<tr class="even">
<td>2018</td>
<td>21,0027464972455</td>
<td>22,0715624579547</td>
<td>5,17429153955024</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>18,5915277970883</td>
<td>19,0362497386225</td>
<td>5,01928768046282</td>
</tr>
<tr class="even">
<td>2020</td>
<td>17,3311682848923</td>
<td>15,6410071153504</td>
<td>-2,06551182934165</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>21,4165556390653</td>
<td>18,7882026359018</td>
<td>3,70288562827751</td>
</tr>
<tr class="even">
<td>2022</td>
<td>24,5037442007268</td>
<td>20,9621544809476</td>
<td>5,30741934775764</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>21,7465817671945</td>
<td>19,5690849947929</td>
<td>5,04810577067288</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2013-2023, data yang dipakai ialah data yang telah diolah dengan sumber world Development indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"F:/Tugas metopel"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Metopen2<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"tabeleksporimpor.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>Metopen2, X<span class="sc">~</span>Y )</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = X ~ Y, data = Metopen2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6607 -0.6113 -0.3077  0.4742  2.9070 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   6.9623     3.3496   2.079  0.06742 . 
Y             0.6981     0.1636   4.268  0.00209 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.383 on 9 degrees of freedom
Multiple R-squared:  0.6693,    Adjusted R-squared:  0.6325 
F-statistic: 18.21 on 1 and 9 DF,  p-value: 0.002087</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>Metopen2<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Metopen2<span class="sc">$</span>X,Metopen2<span class="sc">$</span>Y, <span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span> <span class="st">'purple'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot pengaruh terhadap nilai Ekspor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Metopen2<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Metopen2<span class="sc">$</span>X,Metopen2<span class="sc">$</span>Y,<span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span> <span class="st">'pink'</span>, <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot pengaruh terhadap nilai Impor</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menggunakan analisis regresi linier sederhana untuk melihat pengaruh variabel independen Y terhadap variabel dependen X :</p>
<p><span class="math display">\[
X_ =\beta_0 + \beta_1 Y+\epsilon
\]</span> di mana <span class="math inline">\(\beta_0\)</span> adalah intercept, <span class="math inline">\(\beta_1\)</span> adalah koefisien regresi, dan <span class="math inline">\(\epsilon\)</span> adalah error. Pengujian dilakukan dengan uji <span class="math inline">\(t\)</span> untuk mengetahui signifikansi pengaruh variabel independen, dan uji <span class="math inline">\(F\)</span> untuk menilai signifikansi model secara keseluruhan. Kesesuaian model dievaluasi menggunakan nilai <span class="math inline">\(R^2\)</span> dan adjusted <span class="math inline">\(R^2\)</span> yang menunjukkan seberapa baik variabel independen menjelaskan variabel dependen. Hasil analisis ini digunakan untuk menginterpretasikan hubungan antara Y dan X.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Koefisien</th>
<th>Std,error</th>
<th>t-value</th>
<th>p-value</th>
<th>kesimpulan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>6,9623</td>
<td>3,3496</td>
<td>2,079</td>
<td>0,06742</td>
<td>Tidak signifikan (.)</td>
</tr>
<tr class="even">
<td>Y (koefisien)</td>
<td>0,6981</td>
<td>0,1636</td>
<td>4,268</td>
<td>0,00209</td>
<td>Signifikan (**)</td>
</tr>
<tr class="odd">
<td>R-Squared</td>
<td>0,6693</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0,6325</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Residual Standard Error</td>
<td>1,383</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>F-statistic</td>
<td>18,21</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[X=6.9623+0.6981×Y\]</span></p>
<p>Di mana, Intercept (6.9623) menunjukkan nilai prediksi X ketika nilai Y sama dengan nol. Koefisien untuk Y (0.6981) menunjukkan bahwa setiap kenaikan satu unit pada Y akan meningkatkan X sebesar 0.6981 unit. Residual merupakan selisih antara nilai aktual dan nilai yang diprediksi oleh model. Berdasarkan hasil analisis, residual memiliki distribusi yang cukup baik dengan nilai minimum -1.6607 dan maksimum 2.9070. Median residual sebesar -0.3077 menunjukkan bahwa sebagian besar residual dekat dengan nol, menandakan model memprediksi dengan baik. Berdasarkan kuartil, 25% residual berada di bawah -0.6113 dan 25% sisanya berada di atas 0.4742, menunjukkan bahwa sebagian besar residual terdistribusi dengan baik, meskipun ada beberapa nilai ekstrem (outlier) pada bagian residual positif.</p>
<p>Koefisien regresi untuk intercept adalah 6.9623, yang berarti ketika Y = 0, nilai prediksi X adalah 6.9623. Sedangkan koefisien untuk Y adalah 0.6981, yang menunjukkan bahwa setiap kenaikan satu unit pada Y akan menyebabkan kenaikan 0.6981 unit pada X.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span> Metopen2, Y<span class="sc">~</span>X )</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = X ~ Y, data = Metopen2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6607 -0.6113 -0.3077  0.4742  2.9070 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   6.9623     3.3496   2.079  0.06742 . 
Y             0.6981     0.1636   4.268  0.00209 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.383 on 9 degrees of freedom
Multiple R-squared:  0.6693,    Adjusted R-squared:  0.6325 
F-statistic: 18.21 on 1 and 9 DF,  p-value: 0.002087</code></pre>
</div>
</div>
<p>Analisis regresi ini bertujuan untuk mengidentifikasi hubungan antara variabel Y dan X. Hasil regresi menunjukkan bahwa variabel Y memiliki pengaruh signifikan terhadap X, dengan koefisien regresi sebesar 0.6981. Artinya, setiap kenaikan satu unit pada Y akan meningkatkan X sebesar 0.6981 unit. Uji signifikansi menunjukkan bahwa koefisien Y signifikan (p-value = 0.00209), sementara intercept tidak signifikan (p-value = 0.06742). Model ini mampu menjelaskan 66.93% variasi dalam X (Multiple R-squared = 0.6693), dengan residual standard error 1.383 yang menunjukkan akurasi prediksi model. Uji F juga menunjukkan bahwa model regresi secara keseluruhan signifikan (p-value = 0.002087). Secara keseluruhan, model regresi ini menunjukkan hubungan yang signifikan dan dapat digunakan untuk prediksi X berdasarkan Y.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Kesimpulan mengenai pengaruh ekspor dan impor terhadap risiko ekonomi menunjukkan bahwa keduanya memiliki dampak yang saling terkait. Ekspor dapat meningkatkan pendapatan negara dan mendorong pertumbuhan ekonomi, namun terlalu bergantung pada ekspor dapat membuat ekonomi rentan terhadap fluktuasi harga global dan permintaan internasional. Di sisi lain, impor memungkinkan pemenuhan kebutuhan dalam negeri yang tidak dapat diproduksi secara efisien, namun jika impor lebih tinggi daripada ekspor, dapat menyebabkan defisit neraca perdagangan yang berisiko terhadap kestabilan mata uang dan cadangan devisa. Oleh karena itu, keseimbangan antara ekspor dan impor perlu dijaga untuk meminimalkan risiko ekonomi yang timbul akibat ketergantungan pada perdagangan internasional.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p><strong>Sari, A. F., &amp; Sudiana, I. N. (2018).</strong> <em>Pengaruh Ekspor dan Impor Terhadap Pertumbuhan Ekonomi Indonesia: Pendekatan Model ECM (Error Correction Model)</em>. Jurnal Ekonomi dan Pembangunan, 26(2), 134-145.</p>
<p><strong>Haryanto, E., &amp; Adi, R. (2019).</strong> <em>Analisis Pengaruh Ekspor dan Impor Terhadap Pertumbuhan Ekonomi di Indonesia Tahun 2000-2018</em>. Jurnal Ekonomi dan Keuangan, 23(3), 215-227.</p>
<p><strong>Pratiwi, D., &amp; Arifin, Z. (2020).</strong> <em>Pengaruh Ekspor dan Impor terhadap Pertumbuhan Ekonomi di Negara Berkembang: Kasus Indonesia</em>. Jurnal Pembangunan Ekonomi, 28(1), 88-102.</p>
<p><strong>Gunawan, W. (2021).</strong> <em>Dampak Ekspor dan Impor terhadap Pertumbuhan Ekonomi Indonesia: Analisis Data Panel</em>. Jurnal Ekonomi Indonesia, 34(4), 324-335.</p>
<p><strong>WDI.</strong> <em>(World Development Indicators) Tahun 2013 - 2023 tentang GDP Growth Dan Nilai ekspor &amp; impor.</em></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>